# Generated by Django 4.1.7 on 2023-03-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2day', '0002_customer_joined_date_customer_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beginning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
